### ISSUE TITLE
Identify mistyped space

### ISSUE THREAD

**Issue by AmiMappy** [sugarlabs/typing-turtle-activity#9]
This is more of an enhancement than a real issue.
It would would be nice if the mistyped spaces could be represented with a red underscore(_)

**Comment by chimosky** [comment]
@AmiMappy whatever input entered in the activity is expected to be what the activity asks and anything else would be represented as the key typed but it's colour would be red.

It won't be great if you entered `j` where you're supposed to enter a space and then see an underscore instead of the `j` you entered.

**Comment by wadetb** [comment]
The underscore idea makes sense to me, since a space marked in red would be by definition invisible.

(Also- awesome to hear that people still use Typing Turtle!)

**Comment by quozl** [comment]
I agree with @AmiMappy.  Here's what it looks like if you type a space when you should have typed a letter;

![tmp](https://user-images.githubusercontent.com/2936481/70215395-8064ae00-1791-11ea-9d91-dfdb5a0432f4.png)

**Comment by Aniket21mathur** [comment]
I agree with @AmiMappy as well, seems like a valid issue
